name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Deploy application files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: 82.198.229.239
          username: u884912930
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: ./
          server-dir: /public_html/tst/
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/.env
            **/.env.*
            **/node_modules/**
            **/vendor/**
            **/storage/**
            **/tests/**
            **/docs/**
            **/.phpunit.result.cache
            **/phpunit.xml
